// tb_decode.sv
// Constrained-random unit testbench for the ID stage.
//
// Random legal instructions are generated by picking an encoding class and
// randomising its fields, then assembled into a word. The expected control
// bundle is derived from the ISA definition independently of the RTL, so a
// transcription slip in decode.sv (wrong funct7 gate, swapped srcA/srcB,
// mis-shuffled immediate) shows up as a mismatch.

`timescale 1ns/1ps

module tb_decode;
    import pipeline_pkg::*;

    localparam int N_TXN = 6000;

    logic       clk = 1'b0;
    logic       rst, stall, flush;
    if_id_t     if_id;
    logic [4:0] rs1_addr, rs2_addr;
    logic [31:0] rs1_data, rs2_data;
    logic       uses_rs1, uses_rs2;
    id_ex_t     id_ex;

    always #5 clk = ~clk;

    decode dut (
        .clk (clk), .rst (rst), .stall (stall), .flush (flush),
        .if_id_reg (if_id),
        .rs1_addr (rs1_addr), .rs2_addr (rs2_addr),
        .rs1_data (rs1_data), .rs2_data (rs2_data),
        .uses_rs1 (uses_rs1), .uses_rs2 (uses_rs2),
        .id_ex_reg (id_ex)
    );

    int errors = 0, checks = 0;
    int kind_hits [9];

    typedef enum int {
        K_R = 0, K_IALU = 1, K_LOAD = 2, K_STORE = 3, K_BRANCH = 4,
        K_LUI = 5, K_AUIPC = 6, K_JAL = 7, K_JALR = 8
    } kind_e;

    class instr_txn;
        rand int        kind;
        rand bit [4:0]  rd, rs1, rs2;
        rand bit [2:0]  funct3;
        rand bit        f7b5;
        rand bit [11:0] imm12;
        rand bit [19:0] imm20;
        rand bit [20:0] imm21;
        rand bit [31:0] pc;

        constraint c_kind { kind inside {[0:8]}; }
        // legal funct3 values per encoding class
        constraint c_f3 {
            (kind == K_LOAD)   -> funct3 inside {3'b000, 3'b001, 3'b010, 3'b100, 3'b101};
            (kind == K_STORE)  -> funct3 inside {3'b000, 3'b001, 3'b010};
            (kind == K_BRANCH) -> funct3 inside {3'b000, 3'b001, 3'b100, 3'b101, 3'b110, 3'b111};
            (kind == K_JALR)   -> funct3 == 3'b000;
        }
        constraint c_pc  { pc[1:0] == 2'b00; }
        constraint c_j21 { imm21[0] == 1'b0; }
        // exercise rd == x0 often: reg_write must be suppressed
        constraint c_rd  { rd dist { 5'd0 := 20, [5'd1:5'd31] :/ 80 }; }
    endclass

    // -------------------------------------------------------------------------
    function automatic logic [31:0] build_instr(input instr_txn t);
        case (t.kind)
            K_R:      return {(t.f7b5 ? 7'b0100000 : 7'b0000000), t.rs2, t.rs1, t.funct3, t.rd, 7'b0110011};
            K_IALU:   return {(t.funct3 inside {3'b001, 3'b101}) ?
                                  {(t.f7b5 ? 7'b0100000 : 7'b0000000), t.rs2} : t.imm12,
                              t.rs1, t.funct3, t.rd, 7'b0010011};
            K_LOAD:   return {t.imm12, t.rs1, t.funct3, t.rd, 7'b0000011};
            K_STORE:  return {t.imm12[11:5], t.rs2, t.rs1, t.funct3, t.imm12[4:0], 7'b0100011};
            K_BRANCH: return {t.imm21[12], t.imm21[10:5], t.rs2, t.rs1, t.funct3,
                              t.imm21[4:1], t.imm21[11], 7'b1100011};
            K_LUI:    return {t.imm20, t.rd, 7'b0110111};
            K_AUIPC:  return {t.imm20, t.rd, 7'b0010111};
            K_JAL:    return {t.imm21[20], t.imm21[10:1], t.imm21[11], t.imm21[19:12], t.rd, 7'b1101111};
            K_JALR:   return {t.imm12, t.rs1, 3'b000, t.rd, 7'b1100111};
            default:  return 32'h0;
        endcase
    endfunction

    function automatic logic [31:0] exp_imm(input instr_txn t, input logic [31:0] instr);
        case (t.kind)
            K_IALU, K_LOAD, K_JALR:
                return {{20{instr[31]}}, instr[31:20]};
            K_STORE:
                return {{20{t.imm12[11]}}, t.imm12};
            K_BRANCH:
                return {{19{t.imm21[12]}}, t.imm21[12:0]};
            K_LUI, K_AUIPC:
                return {t.imm20, 12'b0};
            K_JAL:
                return {{11{t.imm21[20]}}, t.imm21[20:0]};
            default:
                return 32'h0;
        endcase
    endfunction

    function automatic alu_op_t exp_alu_op(input instr_txn t);
        case (t.kind)
            K_R: case (t.funct3)
                     3'b000: return t.f7b5 ? ALU_SUB : ALU_ADD;
                     3'b001: return ALU_SLL;
                     3'b010: return ALU_SLT;
                     3'b011: return ALU_SLTU;
                     3'b100: return ALU_XOR;
                     3'b101: return t.f7b5 ? ALU_SRA : ALU_SRL;
                     3'b110: return ALU_OR;
                     default: return ALU_AND;
                 endcase
            K_IALU: case (t.funct3)
                     3'b000: return ALU_ADD;         // ADDI never checks funct7
                     3'b001: return ALU_SLL;
                     3'b010: return ALU_SLT;
                     3'b011: return ALU_SLTU;
                     3'b100: return ALU_XOR;
                     3'b101: return t.f7b5 ? ALU_SRA : ALU_SRL;
                     3'b110: return ALU_OR;
                     default: return ALU_AND;
                 endcase
            K_BRANCH: case (t.funct3[2:1])
                     2'b00:   return ALU_SUB;
                     2'b10:   return ALU_SLT;
                     2'b11:   return ALU_SLTU;
                     default: return ALU_SUB;
                 endcase
            K_LUI:   return ALU_COPY_B;
            default: return ALU_ADD;
        endcase
    endfunction

    // -------------------------------------------------------------------------
    task automatic check_field(input string name, input logic [31:0] got, exp,
                               input logic [31:0] instr);
        checks++;
        if (got !== exp) begin
            $display("  FAIL  instr=0x%08x  %-12s got 0x%08x, expected 0x%08x",
                     instr, name, got, exp);
            errors++;
        end
    endtask

    initial begin
        instr_txn t = new();
        logic [31:0] instr;
        bit e_regw, e_memr, e_memw, e_m2r, e_br, e_jmp, e_jalr, e_u1, e_u2;
        alu_srca_t e_srca;
        alu_srcb_t e_srcb;

        $display("");
        $display("======== tb_decode: %0d constrained-random instructions ========", N_TXN);

        rst = 1'b1; stall = 1'b0; flush = 1'b0;
        if_id = '0; rs1_data = 32'd0; rs2_data = 32'd0;
        repeat (3) @(posedge clk);
        rst = 1'b0;

        for (int i = 0; i < N_TXN; i++) begin
            @(negedge clk);
            if (!t.randomize()) begin
                $display("  FAIL  randomize() failed"); errors++; break;
            end
            instr = build_instr(t);
            kind_hits[t.kind]++;

            if_id.instr = instr;
            if_id.pc    = t.pc;
            if_id.valid = 1'b1;
            rs1_data    = 32'hA5A5_0000 + i;
            rs2_data    = 32'h5A5A_0000 + i;

            // expected control
            e_regw = (t.kind inside {K_R, K_IALU, K_LOAD, K_LUI, K_AUIPC, K_JAL, K_JALR})
                     && (t.rd != 5'd0);
            e_memr = (t.kind == K_LOAD);
            e_memw = (t.kind == K_STORE);
            e_m2r  = (t.kind == K_LOAD);
            e_br   = (t.kind == K_BRANCH);
            e_jmp  = (t.kind inside {K_JAL, K_JALR});
            e_jalr = (t.kind == K_JALR);
            e_u1   = (t.kind inside {K_R, K_IALU, K_LOAD, K_STORE, K_BRANCH, K_JALR});
            e_u2   = (t.kind inside {K_R, K_STORE, K_BRANCH});

            e_srca = (t.kind inside {K_AUIPC, K_JAL, K_JALR}) ? SRCA_PC : SRCA_RS1;
            case (t.kind)
                K_R, K_BRANCH:      e_srcb = SRCB_RS2;
                K_JAL, K_JALR:      e_srcb = SRCB_FOUR;
                default:            e_srcb = SRCB_IMM;
            endcase

            #1;
            // combinational outputs are valid now, before the clock edge
            check_field("uses_rs1", uses_rs1, e_u1, instr);
            check_field("uses_rs2", uses_rs2, e_u2, instr);

            @(posedge clk);
            #1;
            // registered bundle
            check_field("alu_op",     id_ex.alu_op,     exp_alu_op(t),        instr);
            check_field("alu_srca",   id_ex.alu_srca,   e_srca,               instr);
            check_field("alu_srcb",   id_ex.alu_srcb,   e_srcb,               instr);
            check_field("imm",        id_ex.imm,        exp_imm(t, instr),    instr);
            check_field("reg_write",  id_ex.reg_write,  e_regw,               instr);
            check_field("mem_read",   id_ex.mem_read,   e_memr,               instr);
            check_field("mem_write",  id_ex.mem_write,  e_memw,               instr);
            check_field("mem_to_reg", id_ex.mem_to_reg, e_m2r,                instr);
            check_field("branch",     id_ex.branch,     e_br,                 instr);
            check_field("jump",       id_ex.jump,       e_jmp,                instr);
            check_field("jalr",       id_ex.jalr,       e_jalr,               instr);
            // instr[11:7] is the rd field for R/I/U/J, but immediate bits for
            // S/B -- decode extracts it unconditionally and reg_write gates it
            check_field("rd_addr",    id_ex.rd_addr,    instr[11:7],          instr);
            check_field("pc",         id_ex.pc,         t.pc,                 instr);
        end

        for (int k = 0; k <= 8; k++) begin
            checks++;
            if (kind_hits[k] < 50) begin
                $display("  FAIL  encoding class %0d only hit %0d times", k, kind_hits[k]);
                errors++;
            end
        end

        $display("  encoding class hits: %p", kind_hits);
        if (errors == 0) $display("  tb_decode: %0d checks PASSED", checks);
        else             $display("  tb_decode: %0d of %0d checks FAILED", errors, checks);

        $finish;
    end

endmodule
